services:
  - type: web
    name: tiktokanalysebot
    env: docker   # <-- MUST BE docker to use Dockerfile
    startCommand: node index.js  # You can keep this or remove because CMD in Dockerfile runs this
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false