services:
  - type: web
    name: tiktokanalysebot
    env: node
    buildCommand: |
      npm install
      npx playwright install chromium
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false