services:
  - type: web
    name: tiktokanalysebot
    env: docker
    dockerfilePath: ./Dockerfile
    # Build & start commands are handled by the Dockerfile, so no need to specify here.
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
