services:
  - type: web
    name: tiktokanalysebot
    env: docker
    plan: free
    branch: main 
    region: frankfurt 
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false