services:
  - type: web
    name: tiktokanalysebot
    env: docker
    plan: free
    branch: main # or your active branch
    region: frankfurt # or your closest region
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false