services:
  - type: web
    name: tiktokanalysebot
    env: docker  # ✅ this enables Dockerfile usage
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
